# -*- mode: python ; coding: utf-8 -*-
#
# Hand-maintained (not auto-generated by `pyi-makespec`) so we can prune
# Qt/PySide6 bloat that no PyInstaller CLI flag can reach: individual
# files inside collected plugin folders, and the translations PyInstaller's
# Qt hook always pulls in for every locale Qt ships. `build_exe.py` runs
# this via `pyinstaller tx_controller.spec` instead of passing --name/
# --icon/--add-data/etc. on the command line - once you point PyInstaller
# at a .spec file it skips makespec entirely, so all of that now lives
# here as real Analysis()/EXE()/COLLECT() arguments instead.
#
# See build_exe.py for PRUNE_QT_EXTRAS (env var to disable everything
# below without editing this file) and for what each pruned category is.

import os
import sys

sys.path.insert(0, SPECPATH)
import build_exe as cfg

a = Analysis(
    [cfg.MAIN_SCRIPT],
    pathex=[],
    binaries=[],
    datas=[tuple(entry.split(os.pathsep, 1)) for entry in cfg.ADD_DATA],
    hiddenimports=cfg.HIDDEN_IMPORTS,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=cfg.UNUSED_QT_MODULES,
    noarchive=False,
)

if cfg.PRUNE_QT_EXTRAS:
    a.binaries, a.datas = cfg.prune_qt_extras(a.binaries, a.datas)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="TX Controller",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=bool(cfg.UPX_DIR),
    upx_exclude=cfg.UPX_EXCLUDE,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=[cfg.ICON_ICO],
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=bool(cfg.UPX_DIR),
    upx_exclude=cfg.UPX_EXCLUDE,
    name="TX Controller",
)
